//! The TS/JS glue that macros import, embedded in the binary.
//!
//! Macros (including `lodestone-macro-lib` and the generic instance bootstrap)
//! import the glue by URLs such as
//! `https://raw.githubusercontent.com/Lodestone-Team/lodestone/dev/core/src/deno_ops/events/events.ts`.
//! That is upstream's repository, which can change at any time and can differ
//! from this build. The module loader serves every URL under one of
//! [`EMBEDDED_GLUE_URL_PREFIXES`] from the copies embedded here, and never
//! fetches it.
//!
//! The table is generated by `build.rs` from the directories listed there.

include!(concat!(env!("OUT_DIR"), "/embedded_glue.rs"));

/// URL prefixes served from the embedded glue. The rest of the URL is the path
/// of the file under `core/`.
///
/// The specifier keeps its URL, so relative imports inside an embedded file
/// resolve under the same prefix and are also served from here.
pub const EMBEDDED_GLUE_URL_PREFIXES: &[&str] =
    &["https://raw.githubusercontent.com/Lodestone-Team/lodestone/dev/core/"];

/// If `specifier` is under one of [`EMBEDDED_GLUE_URL_PREFIXES`], return its
/// path under `core/`.
pub fn glue_path(specifier: &str) -> Option<&str> {
    EMBEDDED_GLUE_URL_PREFIXES
        .iter()
        .find_map(|prefix| specifier.strip_prefix(prefix))
}

/// The contents of the embedded file at `path` under `core/`.
pub fn get_glue(path: &str) -> Option<&'static str> {
    EMBEDDED_GLUE
        .binary_search_by(|(p, _)| (*p).cmp(path))
        .ok()
        .map(|i| EMBEDDED_GLUE[i].1)
}

#[cfg(test)]
mod tests {
    use std::path::{Component, Path, PathBuf};

    use super::{get_glue, glue_path, EMBEDDED_GLUE, EMBEDDED_GLUE_URL_PREFIXES};

    #[test]
    fn table_contains_the_glue() {
        for path in [
            "src/deno_ops/prelude/prelude.ts",
            "src/deno_ops/events/events.ts",
            "src/deno_ops/instance_control/instance_control.ts",
            "deno_bindings/TaskPID.ts",
            "src/implementations/generic/js/main/mod.ts",
            "src/implementations/generic/js/main/libs/procedure_bridge.ts",
        ] {
            let on_disk =
                std::fs::read_to_string(Path::new(env!("CARGO_MANIFEST_DIR")).join(path)).unwrap();
            assert_eq!(get_glue(path), Some(on_disk.as_str()), "{path}");
        }
        assert_eq!(get_glue("src/main.rs"), None);
        assert!(EMBEDDED_GLUE.windows(2).all(|w| w[0].0 < w[1].0), "sorted");
    }

    #[test]
    fn prefix_matching() {
        let prefix = EMBEDDED_GLUE_URL_PREFIXES[0];
        assert_eq!(
            glue_path(&format!("{prefix}src/deno_ops/events/events.ts")),
            Some("src/deno_ops/events/events.ts")
        );
        assert_eq!(
            glue_path("https://raw.githubusercontent.com/Lodestone-Team/lodestone-macro-lib/main/events.ts"),
            None
        );
    }

    /// Relative specifiers in `import ... from "./x"` / `export ... from "../x"`.
    ///
    /// `import type` and `export type` are skipped: the transpiler removes
    /// them, so their targets are never loaded. (Some generated bindings have
    /// type imports of files that do not exist, e.g. `./MacroPID.ts` in
    /// `deno_bindings/MacroEvent.ts`.)
    fn relative_imports(source: &str) -> Vec<String> {
        let mut specifiers = Vec::new();
        for quote in ['"', '\''] {
            let needle = format!("from {quote}.");
            let mut offset = 0;
            while let Some(found) = source[offset..].find(&needle) {
                let start = offset + found + needle.len() - 1;
                let end = start
                    + source[start..]
                        .find(quote)
                        .expect("unterminated import specifier");
                let before = &source[..start];
                let statement = before
                    .rfind("import")
                    .max(before.rfind("export"))
                    .map_or("", |i| &before[i..]);
                let type_only =
                    statement.starts_with("import type ") || statement.starts_with("export type ");
                if !type_only {
                    specifiers.push(source[start..end].to_string());
                }
                offset = end;
            }
        }
        specifiers
    }

    fn normalize(path: &Path) -> String {
        let mut out = PathBuf::new();
        for component in path.components() {
            match component {
                Component::ParentDir => {
                    assert!(out.pop(), "import escapes core/: {}", path.display());
                }
                Component::CurDir => {}
                other => out.push(other),
            }
        }
        out.components()
            .map(|c| c.as_os_str().to_string_lossy().into_owned())
            .collect::<Vec<_>>()
            .join("/")
    }

    /// Every relative import in an embedded file must resolve to another
    /// embedded file, or loading it through the URL prefix would fail.
    #[test]
    fn relative_imports_resolve_inside_the_table() {
        let mut checked = 0;
        for (path, source) in EMBEDDED_GLUE {
            let dir = Path::new(path).parent().unwrap();
            for specifier in relative_imports(source) {
                let target = normalize(&dir.join(&specifier));
                assert!(
                    get_glue(&target).is_some(),
                    "{path} imports {specifier}, but core/{target} is not embedded"
                );
                checked += 1;
            }
        }
        assert!(checked >= 10, "only {checked} imports found");
    }
}
